import type { Account, RecurringTransaction } from '../types';

export const MOCK_ACCOUNTS: Account[] = [
  {
    id: 'acc-01',
    institutionName: 'Chase',
    accountName: 'Sapphire Reserve',
    accountNumberMask: '4521',
    type: 'credit_card',
    balance: -2104.82,
    creditLimit: 10000,
    availableCredit: 7895.18,
    creditUtilization: 0.21,
    isManual: false,
    isHidden: false,
    excludeFromNetWorth: false,
    connectionStatus: 'healthy',
    lastSyncedAt: '2026-03-12T08:00:00Z',
    balanceHistory: [],
  },
  {
    id: 'acc-02',
    institutionName: 'Apple',
    accountName: 'Apple Card',
    accountNumberMask: '8812',
    type: 'credit_card',
    balance: -1320.14,
    creditLimit: 5000,
    availableCredit: 3679.86,
    creditUtilization: 0.26,
    isManual: false,
    isHidden: false,
    excludeFromNetWorth: false,
    connectionStatus: 'healthy',
    lastSyncedAt: '2026-03-12T08:00:00Z',
    balanceHistory: [],
  },
  {
    id: 'acc-03',
    institutionName: 'Chase',
    accountName: 'Total Checking',
    accountNumberMask: '7732',
    type: 'checking',
    balance: 6120.48,
    isManual: false,
    isHidden: false,
    excludeFromNetWorth: false,
    connectionStatus: 'healthy',
    lastSyncedAt: '2026-03-12T08:00:00Z',
    balanceHistory: [],
  },
  {
    id: 'acc-04',
    institutionName: 'Ally',
    accountName: 'Online Savings',
    accountNumberMask: '3390',
    type: 'savings',
    balance: 2520.0,
    isManual: false,
    isHidden: false,
    excludeFromNetWorth: false,
    connectionStatus: 'healthy',
    lastSyncedAt: '2026-03-12T08:00:00Z',
    balanceHistory: [],
  },
  {
    id: 'acc-05',
    institutionName: 'Fidelity',
    accountName: '401(k)',
    accountNumberMask: '5551',
    type: 'investment',
    balance: 94000.0,
    isManual: false,
    isHidden: false,
    excludeFromNetWorth: false,
    connectionStatus: 'healthy',
    lastSyncedAt: '2026-03-12T08:00:00Z',
    balanceHistory: [],
  },
  {
    id: 'acc-06',
    institutionName: 'Toyota Financial',
    accountName: 'Auto Loan',
    accountNumberMask: '1188',
    type: 'loan',
    balance: -18500.0,
    isManual: false,
    isHidden: false,
    excludeFromNetWorth: false,
    connectionStatus: 'healthy',
    lastSyncedAt: '2026-03-11T06:00:00Z',
    balanceHistory: [],
  },
];

export const MOCK_RECURRINGS: RecurringTransaction[] = [
  {
    id: 'rec-01', name: 'Rent',           emoji: '🏠',
    categoryId: 'cat-03', frequency: 'monthly', status: 'active',
    expectedAmount: -1600, amountMin: 1595, amountMax: 1605,
    expectedDayOfMonth: 1, expectedDayRange: 2,
    nameMatchRule: 'contains', nameMatchValue: 'RENT',
    accountId: 'acc-03', nextExpectedDate: '2026-04-01',
    lastPaidDate: '2026-03-01', isShared: false, sharedSplitPercent: 1.0,
    linkedTransactionIds: ['txn-001', 'txn-051', 'txn-101'],
  },
  {
    id: 'rec-02', name: 'Spotify',        emoji: '🎵',
    categoryId: 'cat-05', frequency: 'monthly', status: 'active',
    expectedAmount: -9.99, amountMin: 9, amountMax: 11,
    expectedDayOfMonth: 23, expectedDayRange: 2,
    nameMatchRule: 'contains', nameMatchValue: 'SPOTIFY',
    accountId: null, nextExpectedDate: '2026-03-23',
    lastPaidDate: '2026-02-23', isShared: false, sharedSplitPercent: 1.0,
    linkedTransactionIds: ['txn-052', 'txn-102'],
  },
  {
    id: 'rec-03', name: 'Netflix',        emoji: '🎬',
    categoryId: 'cat-07', frequency: 'monthly', status: 'active',
    expectedAmount: -15.49, amountMin: 15, amountMax: 16,
    expectedDayOfMonth: 18, expectedDayRange: 2,
    nameMatchRule: 'contains', nameMatchValue: 'NETFLIX',
    accountId: null, nextExpectedDate: '2026-03-18',
    lastPaidDate: '2026-02-18', isShared: false, sharedSplitPercent: 1.0,
    linkedTransactionIds: ['txn-053', 'txn-103'],
  },
  {
    id: 'rec-04', name: 'Planet Fitness', emoji: '🏋️',
    categoryId: 'cat-14', frequency: 'monthly', status: 'active',
    expectedAmount: -24.99, amountMin: 24, amountMax: 26,
    expectedDayOfMonth: 7, expectedDayRange: 2,
    nameMatchRule: 'contains', nameMatchValue: 'PLANET FITNESS',
    accountId: null, nextExpectedDate: '2026-04-07',
    lastPaidDate: '2026-03-07', isShared: false, sharedSplitPercent: 1.0,
    linkedTransactionIds: ['txn-054', 'txn-104'],
  },
  {
    id: 'rec-05', name: 'Internet',       emoji: '📡',
    categoryId: 'cat-12', frequency: 'monthly', status: 'active',
    expectedAmount: -79.99, amountMin: 79, amountMax: 81,
    expectedDayOfMonth: 15, expectedDayRange: 3,
    nameMatchRule: 'contains', nameMatchValue: 'XFINITY',
    accountId: 'acc-03', nextExpectedDate: '2026-03-15',
    lastPaidDate: '2026-02-15', isShared: false, sharedSplitPercent: 1.0,
    linkedTransactionIds: ['txn-055', 'txn-105'],
  },
];
