import type { Transaction } from '../types';

// Helper to build a transaction with defaults
function t(overrides: Partial<Transaction> & Pick<Transaction, 'id' | 'accountId' | 'date' | 'merchantName' | 'originalMerchantName' | 'amount' | 'type' | 'categoryId'>): Transaction {
  return {
    originalDate: overrides.date,
    originalAmount: overrides.amount,
    tipAmount: 0,
    reviewed: true,
    isRecurring: false,
    recurringId: null,
    tags: [],
    notes: '',
    isExcluded: false,
    isSplit: false,
    splitParentId: null,
    splitChildren: [],
    isManual: false,
    currencyCode: 'USD',
    originalCurrencyCode: null,
    originalCurrencyAmount: null,
    ...overrides,
  };
}

export const MOCK_TRANSACTIONS: Transaction[] = [
  // ── MARCH 2026 (in progress through Mar 12) ───────────────────────────────
  t({ id: 'txn-001', accountId: 'acc-03', date: '2026-03-01', merchantName: 'Rent',          originalMerchantName: 'ZELLE PAYMENT RENT',         amount: -1600.00, type: 'regular',           categoryId: 'cat-03', isRecurring: true,  recurringId: 'rec-01' }),
  t({ id: 'txn-002', accountId: 'acc-01', date: '2026-03-02', merchantName: 'Whole Foods',    originalMerchantName: 'WHOLE FOODS MARKET #412',    amount: -87.43,   type: 'regular',           categoryId: 'cat-02' }),
  t({ id: 'txn-003', accountId: 'acc-01', date: '2026-03-03', merchantName: 'Starbucks',      originalMerchantName: 'STARBUCKS #08821',            amount: -6.75,    type: 'regular',           categoryId: 'cat-08', tipAmount: 1.00 }),
  t({ id: 'txn-004', accountId: 'acc-01', date: '2026-03-04', merchantName: 'Chipotle',       originalMerchantName: 'CHIPOTLE MEXICAN GRILL',     amount: -14.50,   type: 'regular',           categoryId: 'cat-01' }),
  t({ id: 'txn-005', accountId: 'acc-03', date: '2026-03-05', merchantName: 'Shell Gas',      originalMerchantName: 'SHELL OIL 574829',           amount: -52.30,   type: 'regular',           categoryId: 'cat-04' }),
  t({ id: 'txn-006', accountId: 'acc-03', date: '2026-03-05', merchantName: 'Payroll',        originalMerchantName: 'DIRECT DEPOSIT ACME CORP',   amount:  4200.00, type: 'income',            categoryId: null }),
  t({ id: 'txn-007', accountId: 'acc-01', date: '2026-03-06', merchantName: 'Amazon',         originalMerchantName: 'AMAZON.COM*2H8K3',           amount: -32.99,   type: 'regular',           categoryId: 'cat-09' }),
  t({ id: 'txn-008', accountId: 'acc-02', date: '2026-03-07', merchantName: 'Planet Fitness', originalMerchantName: 'PLANET FITNESS #0482',       amount: -24.99,   type: 'regular',           categoryId: 'cat-14', isRecurring: true, recurringId: 'rec-04' }),
  t({ id: 'txn-009', accountId: 'acc-01', date: '2026-03-08', merchantName: "Trader Joe's",   originalMerchantName: 'TRADER JOES #221',           amount: -64.17,   type: 'regular',           categoryId: 'cat-02' }),
  t({ id: 'txn-010', accountId: 'acc-02', date: '2026-03-09', merchantName: 'CVS Pharmacy',   originalMerchantName: 'CVS/PHARMACY #7291',         amount: -28.40,   type: 'regular',           categoryId: 'cat-06' }),
  t({ id: 'txn-011', accountId: 'acc-01', date: '2026-03-10', merchantName: 'Nobu Restaurant',originalMerchantName: 'NOBU RESTAURANT 0001',       amount: -82.00,   type: 'regular',           categoryId: 'cat-01', tipAmount: 18.00, reviewed: false }),
  t({ id: 'txn-012', accountId: 'acc-02', date: '2026-03-11', merchantName: 'Target',         originalMerchantName: 'TARGET #0712',               amount: -47.63,   type: 'regular',           categoryId: 'cat-09', reviewed: false }),
  t({ id: 'txn-013', accountId: 'acc-03', date: '2026-03-11', merchantName: 'Lyft',           originalMerchantName: 'LYFT *RIDE SUN 3PM',         amount: -18.75,   type: 'regular',           categoryId: 'cat-04', tipAmount: 3.00, reviewed: false }),
  t({ id: 'txn-014', accountId: 'acc-01', date: '2026-03-12', merchantName: 'Sweetgreen',     originalMerchantName: 'SWEETGREEN 0023 SF',         amount: -16.25,   type: 'regular',           categoryId: 'cat-01', reviewed: false }),

  // ── FEBRUARY 2026 ─────────────────────────────────────────────────────────
  t({ id: 'txn-051', accountId: 'acc-03', date: '2026-02-01', merchantName: 'Rent',           originalMerchantName: 'ZELLE PAYMENT RENT',         amount: -1600.00, type: 'regular',           categoryId: 'cat-03', isRecurring: true,  recurringId: 'rec-01' }),
  t({ id: 'txn-052', accountId: 'acc-01', date: '2026-02-02', merchantName: 'Whole Foods',    originalMerchantName: 'WHOLE FOODS MARKET #412',    amount: -93.21,   type: 'regular',           categoryId: 'cat-02' }),
  t({ id: 'txn-053', accountId: 'acc-02', date: '2026-02-03', merchantName: 'Starbucks',      originalMerchantName: 'STARBUCKS #08821',            amount: -5.95,    type: 'regular',           categoryId: 'cat-08', tipAmount: 1.00 }),
  t({ id: 'txn-054', accountId: 'acc-01', date: '2026-02-05', merchantName: 'Payroll',        originalMerchantName: 'DIRECT DEPOSIT ACME CORP',   amount:  4200.00, type: 'income',            categoryId: null }),
  t({ id: 'txn-055', accountId: 'acc-02', date: '2026-02-07', merchantName: 'Planet Fitness', originalMerchantName: 'PLANET FITNESS #0482',       amount: -24.99,   type: 'regular',           categoryId: 'cat-14', isRecurring: true,  recurringId: 'rec-04' }),
  t({ id: 'txn-056', accountId: 'acc-01', date: '2026-02-08', merchantName: 'Amazon',         originalMerchantName: 'AMAZON.COM*9X2P1',           amount: -54.99,   type: 'regular',           categoryId: 'cat-09' }),
  t({ id: 'txn-057', accountId: 'acc-02', date: '2026-02-10', merchantName: 'Chipotle',       originalMerchantName: 'CHIPOTLE MEXICAN GRILL',     amount: -13.25,   type: 'regular',           categoryId: 'cat-01' }),
  t({ id: 'txn-058', accountId: 'acc-01', date: '2026-02-12', merchantName: "Trader Joe's",   originalMerchantName: 'TRADER JOES #221',           amount: -71.88,   type: 'regular',           categoryId: 'cat-02' }),
  t({ id: 'txn-059', accountId: 'acc-02', date: '2026-02-13', merchantName: 'Walgreens',      originalMerchantName: 'WALGREENS #3291',            amount: -22.18,   type: 'regular',           categoryId: 'cat-06' }),
  t({ id: 'txn-060', accountId: 'acc-01', date: '2026-02-14', merchantName: 'Valentines Dinner',originalMerchantName: 'BISTRO CENTRAL 0044',     amount: -145.00,  type: 'regular',           categoryId: 'cat-01', tipAmount: 29.00, tags: ['Date Night'], notes: "Valentine's Day" }),
  t({ id: 'txn-061', accountId: 'acc-02', date: '2026-02-15', merchantName: 'Xfinity Internet',originalMerchantName: 'XFINITY AUTO PAY',          amount: -79.99,   type: 'regular',           categoryId: 'cat-12', isRecurring: true,  recurringId: 'rec-05' }),
  t({ id: 'txn-062', accountId: 'acc-01', date: '2026-02-16', merchantName: 'Shell Gas',      originalMerchantName: 'SHELL OIL 574829',           amount: -48.00,   type: 'regular',           categoryId: 'cat-04' }),
  t({ id: 'txn-063', accountId: 'acc-02', date: '2026-02-18', merchantName: 'Netflix',        originalMerchantName: 'NETFLIX.COM',                amount: -15.49,   type: 'regular',           categoryId: 'cat-07', isRecurring: true,  recurringId: 'rec-03' }),
  t({ id: 'txn-064', accountId: 'acc-01', date: '2026-02-20', merchantName: 'Haircut',        originalMerchantName: 'GREAT CLIPS #2244',          amount: -25.00,   type: 'regular',           categoryId: 'cat-11', tipAmount: 5.00 }),
  t({ id: 'txn-065', accountId: 'acc-02', date: '2026-02-21', merchantName: 'Spotify',        originalMerchantName: 'SPOTIFY USA',                amount: -9.99,    type: 'regular',           categoryId: 'cat-05', isRecurring: true,  recurringId: 'rec-02' }),
  t({ id: 'txn-066', accountId: 'acc-01', date: '2026-02-22', merchantName: 'Whole Foods',    originalMerchantName: 'WHOLE FOODS MARKET #412',    amount: -55.77,   type: 'regular',           categoryId: 'cat-02' }),
  t({ id: 'txn-067', accountId: 'acc-02', date: '2026-02-24', merchantName: 'Movie Tickets',  originalMerchantName: 'AMC THEATERS #0088',         amount: -31.00,   type: 'regular',           categoryId: 'cat-07' }),
  t({ id: 'txn-068', accountId: 'acc-03', date: '2026-02-25', merchantName: 'Chase CC Payment',originalMerchantName: 'CHASE AUTOPAY CREDIT CARD', amount: -2200.00, type: 'internal_transfer', categoryId: null }),
  t({ id: 'txn-069', accountId: 'acc-01', date: '2026-02-26', merchantName: 'Starbucks',      originalMerchantName: 'STARBUCKS #08821',            amount: -7.45,    type: 'regular',           categoryId: 'cat-08', tipAmount: 1.50 }),
  t({ id: 'txn-070', accountId: 'acc-02', date: '2026-02-28', merchantName: 'Amazon Return',  originalMerchantName: 'AMAZON REFUND*2H8K3',        amount:  32.99,   type: 'regular',           categoryId: 'cat-09', notes: 'Returned item' }),

  // ── JANUARY 2026 ──────────────────────────────────────────────────────────
  t({ id: 'txn-101', accountId: 'acc-03', date: '2026-01-01', merchantName: 'Rent',              originalMerchantName: 'ZELLE PAYMENT RENT',         amount: -1600.00, type: 'regular',           categoryId: 'cat-03', isRecurring: true,  recurringId: 'rec-01' }),
  t({ id: 'txn-102', accountId: 'acc-01', date: '2026-01-03', merchantName: 'Whole Foods',       originalMerchantName: 'WHOLE FOODS MARKET #412',    amount: -102.44,  type: 'regular',           categoryId: 'cat-02' }),
  t({ id: 'txn-103', accountId: 'acc-02', date: '2026-01-04', merchantName: 'Starbucks',         originalMerchantName: 'STARBUCKS #08821',            amount: -6.25,    type: 'regular',           categoryId: 'cat-08', tipAmount: 1.00 }),
  t({ id: 'txn-104', accountId: 'acc-03', date: '2026-01-05', merchantName: 'Payroll',           originalMerchantName: 'DIRECT DEPOSIT ACME CORP',   amount:  4200.00, type: 'income',            categoryId: null }),
  t({ id: 'txn-105', accountId: 'acc-02', date: '2026-01-07', merchantName: 'Planet Fitness',    originalMerchantName: 'PLANET FITNESS #0482',        amount: -24.99,   type: 'regular',           categoryId: 'cat-14', isRecurring: true,  recurringId: 'rec-04' }),
  t({ id: 'txn-106', accountId: 'acc-01', date: '2026-01-09', merchantName: 'Best Buy',          originalMerchantName: 'BEST BUY #0312',             amount: -149.99,  type: 'regular',           categoryId: 'cat-09', notes: 'New keyboard' }),
  t({ id: 'txn-107', accountId: 'acc-01', date: '2026-01-11', merchantName: "Trader Joe's",      originalMerchantName: 'TRADER JOES #221',           amount: -58.33,   type: 'regular',           categoryId: 'cat-02' }),
  t({ id: 'txn-108', accountId: 'acc-02', date: '2026-01-13', merchantName: 'Lyft',              originalMerchantName: 'LYFT *RIDE MON 11PM',        amount: -24.50,   type: 'regular',           categoryId: 'cat-04', tipAmount: 4.00 }),
  t({ id: 'txn-109', accountId: 'acc-01', date: '2026-01-15', merchantName: 'Xfinity Internet',  originalMerchantName: 'XFINITY AUTO PAY',           amount: -79.99,   type: 'regular',           categoryId: 'cat-12', isRecurring: true,  recurringId: 'rec-05' }),
  t({ id: 'txn-110', accountId: 'acc-02', date: '2026-01-16', merchantName: 'Shell Gas',         originalMerchantName: 'SHELL OIL 574829',           amount: -55.10,   type: 'regular',           categoryId: 'cat-04' }),
  t({ id: 'txn-111', accountId: 'acc-01', date: '2026-01-18', merchantName: 'Netflix',           originalMerchantName: 'NETFLIX.COM',                amount: -15.49,   type: 'regular',           categoryId: 'cat-07', isRecurring: true,  recurringId: 'rec-03' }),
  t({ id: 'txn-112', accountId: 'acc-02', date: '2026-01-19', merchantName: 'Chipotle',          originalMerchantName: 'CHIPOTLE MEXICAN GRILL',     amount: -11.75,   type: 'regular',           categoryId: 'cat-01' }),
  t({ id: 'txn-113', accountId: 'acc-01', date: '2026-01-21', merchantName: 'Party Supplies',    originalMerchantName: 'PARTY CITY #0991',           amount: -62.44,   type: 'regular',           categoryId: 'cat-13', tags: ['Party'] }),
  t({ id: 'txn-114', accountId: 'acc-02', date: '2026-01-23', merchantName: 'Spotify',           originalMerchantName: 'SPOTIFY USA',                amount: -9.99,    type: 'regular',           categoryId: 'cat-05', isRecurring: true,  recurringId: 'rec-02' }),
  t({ id: 'txn-115', accountId: 'acc-01', date: '2026-01-24', merchantName: 'Whole Foods',       originalMerchantName: 'WHOLE FOODS MARKET #412',    amount: -79.90,   type: 'regular',           categoryId: 'cat-02' }),
  t({ id: 'txn-116', accountId: 'acc-02', date: '2026-01-25', merchantName: 'Doctor Copay',      originalMerchantName: 'UCSF HEALTH PAYMENT',        amount: -40.00,   type: 'regular',           categoryId: 'cat-06' }),
  t({ id: 'txn-117', accountId: 'acc-03', date: '2026-01-26', merchantName: 'Chase CC Payment',  originalMerchantName: 'CHASE AUTOPAY CREDIT CARD', amount: -2450.00, type: 'internal_transfer', categoryId: null }),
  t({ id: 'txn-118', accountId: 'acc-01', date: '2026-01-28', merchantName: 'Starbucks',         originalMerchantName: 'STARBUCKS #08821',            amount: -6.50,    type: 'regular',           categoryId: 'cat-08', tipAmount: 1.00 }),
  t({ id: 'txn-119', accountId: 'acc-02', date: '2026-01-29', merchantName: 'Target',            originalMerchantName: 'TARGET #0712',               amount: -38.14,   type: 'regular',           categoryId: 'cat-09' }),
  t({ id: 'txn-120', accountId: 'acc-01', date: '2026-01-31', merchantName: 'Electric Bill',     originalMerchantName: 'PG&E AUTO PAY',              amount: -88.22,   type: 'regular',           categoryId: 'cat-12' }),
];
